name: Build OpenChrome
on: [push] # Parte ogni volta che salvi un file

jobs:
  create-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepara Ambiente
        run: |
          sudo apt update
          sudo apt install -y squashfs-tools xorriso

      - name: Costruisci OpenChrome
        run: |
          chmod +x build.sh
          sudo ./build.sh
          # Qui GitHub sta lavorando per te!
          
